---
apiVersion: v1
kind: Secret
metadata:
  name: admin-auth-secret

data:
  users: YWRtaW46JDJ5JDEwJERNeU15eDkxLjk1M0dLdXJiRFpldXU4WlBpb2QyNnhnZVdYVXl6WUcuLzl1VlNmZy5YUmhp

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-auth

spec:
  basicAuth:
    secret: admin-auth-secret

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-dashboard-redirect

spec:
  redirectRegex:
    permanent: true
    regex: ^(.*)/$
    replacement: ${1}/dashboard/

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress-route

spec:
  entryPoints: ["admin"]
  routes:
    - match: Path(`/`)
      kind: Rule
      middlewares:
        - name: admin-dashboard-redirect

      services:
        - name: dashboard@internal
          kind: TraefikService
          port: 8080

    - match: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      kind: Rule
      middlewares:
        - name: admin-auth

      services:
        - name: api@internal
          kind: TraefikService
          port: 8080
